version: 2
jobs:
  build:
    docker: ## Should be node version 6.4 but it does not exist as a cicleci image
      - image: circleci/node:6.10
    steps:
      - checkout
      - run: echo "A first hello"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test